### ISSUE TITLE
Request: Please add TSX support

### ISSUE THREAD

**Issue by JoeArizona** [klauspost/cpuid#15]
At first it seemed simple to just do the PR myself, but there were parts of the code I didn't understand, so I'm requesting the change instead...

Intel's [Transactional Synchronization Extensions (TSX)](https://en.wikipedia.org/wiki/Transactional_Synchronization_Extensions) support is somewhat unpredictable, given that there was a bug that led it to be disabled in Haswell and many Broadwell CPUs, and that it's not included in every Skylake and Kaby Lake model. So having it in CPUID would be especially helpful.

**Comment by klauspost** [comment]
Detection of TSX is split into HLE (Hardware Lock Elision) and RTM (Restricted Transactional Memory) detection. It would seem like `TSX = HLE & RTM` in general terms. Both of which are available.

I will add a separate function for this.I have not had the chance to verify this on hardware, so please so that if possible.

**Comment by klauspost** [comment]
Added to master.
