### ISSUE TITLE
Request: report number of physical chips

### ISSUE THREAD

**Issue by shoenig** [klauspost/cpuid#4]
AFAICT there's no way to know how many physical processors exist, as cpuid only reports information for the cpu the current goroutine is running on. It would be very useful (for NUMA aware programs) to have the equivelent of

```
physical id : 0
siblings    : 8
core id     : 3
cpu cores   : 4
```

from /proc/cpuinfo for all physical cpus.

**Comment by klauspost** [comment]
I am a bit unsure about how to do this. I looked at representing the [Intel CPU topology](https://software.intel.com/en-us/articles/intel-64-architecture-processor-topology-enumeration), but it is very complex.

Ultimately I think the only way to really do it is through the runtime, since right now you can be rescheduled to any CPU at any time, and any information I could provide is temporary at best. I remember [Dmitry Vyukov looked at a NUMA-aware scheduler for Go](https://groups.google.com/forum/#!topic/golang-dev/URgnGRzo4HA), but I haven't heard about it for a while.

**Comment by splace** [comment]
bit late but...

how could a CPU know if its in a multi-cpu motherboard anyway?

so doesn't that mean that checking the OS is required (maybe bios), which means parsing the output of /proc/cpuinfo is probably the way to go.

i suppose that could be done in this package? maybe with multiple OS support.

**Comment by mpictor** [comment]
since a goroutine can jump from one core to another, I'm also concerned that the information could be garbled in the (unlikely) event that you have two or more different processor models installed...

**Comment by jpm-canonical** [comment]
I don't believe this issue is fixed. When running the example on a dual chip server, only one of the chips' info is obtained.

Can we reopen this issue?

**Comment by klauspost** [comment]
@jpm-canonical I don't see any reason to re-open, since I don't have any plans to pursue it We have no control over the go scheduler and which CPU happens to execute the code.

You are welcome to open an issue, if you have something actionable to contribute. But it will need at least a working PoC.
